name: deploy_parallel
on:
  push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Step1 - Checkout code
        uses: actions/checkout@v3
      - name: Step2 - Install dependencies
        run: npm ci
      - name: Step3 - Lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Step1 - Checkout code
        uses: actions/checkout@v3
      - name: Step2 - Install dependencies
        run: npm ci
      - name: Step3 - Lint
        run: npm run lint
      - name: Step4 - Run tests
        run: npm test
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step1 - Checkout code
        uses: actions/checkout@v3
      - name: Step2 - Install dependencies
        run: npm ci
      - name: Step3 - Build project
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Step1 - Checkout code
        uses: actions/checkout@v3
      - name: Step2 - Install dependencies
        run: npm ci
      - name: Step3 - Deploy project
        run: echo "Deploying application..."