name: deploy_single_job
on:
  workflow_dispatch:
jobs:
  test_build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Step1 - Checkout code
        uses: actions/checkout@v3
      - name: Step2 - Install dependencies
        run: npm ci
      - name: Step3 - Lint
        run: npm run lint
      - name: Step4 - Run tests
        run: npm test
      - name: Step5 - Build project
        run: npm run build
      - name: Step6 - Deploy project
        run: echo "Deploying application..."